%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/user/Work/Sunday_December4/Matlab-1.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/04 13:38:00

%% Import the data
[~, ~, raw] = xlsread('/Users/user/Work/Sunday_December4/Matlab-1.xlsx','Sheet1');
raw = raw(3:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
X1 = data(:,1);
X2 = data(:,2);
VarName3 = data(:,3);
Y1 = data(:,4);
Y2 = data(:,5);
Y3 = data(:,6);
Y4 = data(:,7);
Y5 = data(:,8);
Y6 = data(:,9);

%% Clear temporary variables
clearvars data raw R;